package com.torryharris.model;

public class Clerk extends Employee{
    private String degree;

    public Clerk(String name, int empId, String designation, float salary, String degree) {
        super(name, empId, designation, salary);
        this.degree = degree;
    }

    public String getDegree() {
        return degree;
    }

    public void setDegree(String degree) {
        this.degree = degree;
    }
    public void generatePayRoll()
    {
        System.out.println("Payroll is generated by "+getName());
    }

    @Override
    public String toString() {
        return "Clerk{" +super.toString()+
                ", degree='" + degree + '\'' +
                '}';
    }
}
